name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Update apt-get
        run: sudo apt-get update

      - name: Install binutils and qemu
        run: sudo apt-get install -y binutils-riscv64-linux-gnu qemu-user

      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - run: opam install . --deps-only --with-test

      - run: opam install qcheck

      - run: opam install ppx_expect

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest